export const CREATE_MEDICATION = "CREATE_MEDICATION";
export const RETRIEVE_MEDICATION = "RETRIEVE_MEDICATION";
export const UPDATE_MEDICATION = "UPDATE_MEDICATION";
export const DELETE_MEDICATION = "DELETE_MEDICATION";
export const DELETE_ALL_MEDICATION = "DELETE_ALL_MEDICATION";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const RETRIEVE_USER = "RETRIEVE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const DELETE_USER = "DELETE_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const RETRIEVE_PAYMENTS = "RETRIEVE_PAYMENTS";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";
export const SEARCH_STORIES = 'SEARCH_STORIES';
export const FETCH_STORIES = 'FETCH_STORIES';